# "version is obsolete, it will be ignored, please remove it to avoid potential confusion"
# version: '3.8'
services:
  ex2_mysql:
    image: mysql:8.0-debian  # Debian ベースに変更
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: ex2
      TZ: 'Asia/Tokyo'
      LANG: C.UTF-8
      LC_CTYPE: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - ex2_network

  ex2_py:
    build: .
    container_name: ex2_container
    depends_on:
      - ex2_mysql
    volumes:
      - .:/app
    entrypoint: ["bash", "/app/entrypoint.sh"]
    environment:
      TZ: 'Asia/Tokyo'
      LANG: C.UTF-8
      LC_CTYPE: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5000:5000"
    networks:
      - ex2_network

networks:
  ex2_network:
    driver: bridge

volumes:
  mysql_data: